// packages/react/src/components/ui/input.tsx
import * as React from 'react';

import { cn } from '@/lib/utils';

export type InputSize = 'default' | 'sm' | 'xs';

const inputVariants = {
  size: {
    default: 'h-10 px-3 py-2',
    sm: 'h-8 px-2 text-xs',
    xs: 'h-6 px-2 text-xs',
  },
};

export interface InputProps extends React.ComponentProps<'input'> {
  sizeVariant?: InputSize;
}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type, sizeVariant = 'default', ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          'flex w-full rounded-md border border-input bg-background text-base ring-offset-background file:h-full file:leading-none file:border-0 file:bg-transparent file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50',
          inputVariants.size[sizeVariant],
          className,
        )}
        ref={ref}
        {...props}
      />
    );
  },
);
Input.displayName = 'Input';

export { Input };

// packages/svelte/src/lib/components/ui/input/input.svelte
<script lang="ts">
  import { cn } from '$lib/utils.js';
  import type { HTMLInputAttributes } from 'svelte/elements';
  import type { InputEvents, InputSize } from './index.js';
  import { inputVariants } from './index.js';

  type $$Props = HTMLInputAttributes & {
    el?: HTMLInputElement;
    sizeVariant?: InputSize;
  };
  type $$Events = InputEvents;

  let className: $$Props['class'] = undefined;
  export let value: $$Props['value'] = undefined;
  export let sizeVariant: InputSize = 'default';
  export { className as class };

  // Workaround for https://github.com/sveltejs/svelte/issues/9305
  // Fixed in Svelte 5, but not backported to 4.x.
  export let readonly: $$Props['readonly'] = undefined;

  // Workaround for https://github.com/huntabyte/shadcn-svelte/issues/480
  // Fixed in shadcn-svelte@next using refs from bits-ui@next
  export let el: $$Props['el'] = undefined;
</script>

<input
  class={cn(
    'border-input bg-background ring-offset-background placeholder:text-muted-foreground focus-visible:ring-ring flex w-full rounded-md border file:h-full file:leading-none file:border-0 file:bg-transparent  file:font-medium focus-visible:outline-none focus-visible:ring-2 disabled:cursor-not-allowed disabled:opacity-50',
    inputVariants.size[sizeVariant],
    className,
  )}
  bind:value
  bind:this={el}
  {readonly}
  on:blur
  on:change
  on:click
  on:focus
  on:focusin
  on:focusout
  on:keydown
  on:keypress
  on:keyup
  on:mouseover
  on:mouseenter
  on:mouseleave
  on:mousemove
  on:paste
  on:input
  on:wheel|passive
  {...$$restProps}
/>
